### ISSUE TITLE
goToCurrentTime does not work correctly

### ISSUE THREAD

**Issue by FeFelten** [thellmund/Android-Week-View#195]
**Describe the bug**
When using `goToCurrentTime` only the scroll of `goToHour` is executed but `goToDate` is ignored.

**To Reproduce**
1. Scroll away from current time and current date
2. Invoke method call for `goToCurrentTime`
3. Now the view scrolls to the correct time, but not the correct date

When using only `goToDate(Calendar.getInstance())` scrolling to the current date works. Therefore, it seems that `goToHour` 'overrides' the scroll of `goToDate`.

**Additional context**
 - Android version: 10
 - Samsung Tablet
 - WeekView version: 5.0.1

Further idea as an improvement:
`goToHour` throws an exception, when the `hour` is outside of `minHour` and `maxHour`. I think the implementation would be more convenient, when the method just moves the `hour` into the range between `minHour` and `maxHour`. Like in the following java code:
`Math.min(Math.max(goToHour, weekView.getMinHour()), weekView.getMaxHour())`

Similar to `toToDate`, where the date is adjusted first.

**Comment by thellmund** [comment]
Thanks for reporting this. Will have a fix ready soon and also implement your suggestion.

**Comment by thellmund** [comment]
Fixed it in 9c371ecc1f382530d718d8be9b071ce07c8f5962. Will push out a new version containing this soon.

**Comment by FeFelten** [comment]
Thanks for the fix.

Can you please also include the enhancement for `goToHour` I suggested in the new version. The bug with scrolling should be fixed by your commit, but in the current version I still can not simply implement a scroll to current time and date functionality. If the currentHour is out of range of min/maxHour an exception will be thrown and because of the private access I could also not use `goToDateWithCompletion`.

**Comment by thellmund** [comment]
Oops, I forgot about that. Making this change now!

**Comment by FeFelten** [comment]
Thank you.

**Comment by thellmund** [comment]
I pushed out version 5.0.2 with this fix. Let me know if you discover any other issues!

**Comment by FeFelten** [comment]
The `goToCurrentTime` method still does not work completely. 

1. In the case when the view is scrolled to the current date, but not current time and you invoke the method nothing happens. The expected behavior would be that in this case the scroll for the current hour is executed. Therefore, it seems that the `onComplete()` function is not always called.

2. Another case I found is when trying to scroll to specific date and hour. In version 4.1.6 one could call goToDate followed by goToHour, which but not work anymore in version 5.0.x. The proposed fix only works for the `goToCurrentTime` because `goToDateWithCompletion` is private.


Can you offer a public method like this:
```
    @PublicApi
    fun goToDateAndTime(date: Calendar, hour: Int) {
        goToDateWithCompletion(date) {
            goToHour(hour)
        }
    }
```


I cannot reopen this issue. Should I create a new one for this problem or keep it in this discussion?

**Comment by thellmund** [comment]
Sorry about that – I missed this scenario. 

You’re right. The `onComplete()` wasn’t called if WeekView was already scrolled to the current date. I have fixed that now and will push out 5.0.3 right away. 

As for (2): This morning, I merged a pull request with a cleaner API. You can find it [here](https://github.com/thellmund/Android-Week-View/pull/198). Does that cover your use case?

**Comment by FeFelten** [comment]
Yes, `scrollToDateTime` should cover the use case I described in (2.)

**Comment by FeFelten** [comment]
And thanks again for the fast fix release.
