### ISSUE TITLE
Problem with processing the date from Calendar

### ISSUE THREAD

**Issue by Kotvitz** [thellmund/Android-Week-View#60]
Hi,
It looks like there is some problem with the `goToDate()` function from the WeekView class. The point is that the function after receiving the date as Calendar type does not go to it. 
For example:
It is the date 9/05/2019. I would like to go to the date 29/08/2021. After calling the `goToDate()` method, only the day changes. The year does not change at all, and the month only when it precedes or is next after the current month. In the case of May, the month can be changed only for April and June, and for no other. My guess is that this bug is on the library side. If you can find and fix it, that's great. If you need a more detailed description, I can prepare a simple application that illustrates this problem :)

**Comment by thellmund** [comment]
Thanks for reporting. You’re right, there was an error from my side. I fixed it with 98a63ee5108a23896a3e966092aea4ebfd29acaa. Please give it a go and let me know if there are any other issues.

**Comment by Kotvitz** [comment]
Thank you for your fix, now I can actually go to the date selected in the calendar, but unfortunately there is yet another bug. Namely, after selecting January or November the application throws the following exception:
```
org.threeten.bp.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
        at org.threeten.bp.temporal.ValueRange.checkValidValue(ValueRange.java:278)
        at org.threeten.bp.temporal.ChronoField.checkValidValue(ChronoField.java:557)
        at org.threeten.bp.LocalDate.withMonth(LocalDate.java:988)
        at com.alamkanak.weekview.MonthLoader.onLoad(MonthLoader.kt:24)
        at com.alamkanak.weekview.EventChipsProvider.loadEvents(EventChipsProvider.java:108)
        at com.alamkanak.weekview.EventChipsProvider.loadEventsAndCalculateEventChipPositions(EventChipsProvider.java:67)
        at com.alamkanak.weekview.EventChipsProvider.loadEventsIfNecessary(EventChipsProvider.java:45)
        at com.alamkanak.weekview.WeekView.onDraw(WeekView.java:152)
```

It is worth noting that Calendar indexes months from 0, i.e. January has index 0 and November 10. The content of the exception suggests that this is also a bug on the library side, so I am asking you for help.

**Comment by thellmund** [comment]
I’ll have another look this weekend.

**Comment by thellmund** [comment]
Had some time right now, so I pushed a fix in 8bf168ef3c3ce833dd0387f3b2a1ac411ff07404. Could you give it a go?

**Comment by Kotvitz** [comment]
I checked this a moment ago and there are no bugs when I choose January, unfortunately November still throws an exception.

**Comment by thellmund** [comment]
Pushed a fix in ff6eebcc7352ec7f083e370209ae89b7be0bcb72. Thanks again for reporting and sorry for all the back-and-forth 🙄

**Comment by Kotvitz** [comment]
Ok, everything is working 👍 Thank you for your valuable help!
